/*2.Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.*/

#include<bits/stdc++.h>
using namespace std;
int main(){
    int term_1 = 0, term_2 = 1, nextTerm = 0, sum=0;
    nextTerm = term_1 + term_2;
    while(nextTerm<=4000000) {
    if(nextTerm%2==0){
        sum+=nextTerm;
    }
    term_1 = term_2;
    term_2 = nextTerm;
    nextTerm = term_1 + term_2;
  }
  cout<<sum;
}


